In [1]:
import torch
import numpy as np
from PIL import Image

In [23]:
def polynomial_fun(w, x):
    """
    Evaluates a polynomial function given the weight vector w and an input scalar variable x.
    Args:
        w (torch.Tensor): Weight vector of size (M + 1, 1)
        x (torch.Tensor): Input scalar variables of size (N, 1)
    Returns:
        y (torch.Tensor): Output value of the polynomial function which has size (N, 1)
    """
    M = w.shape[0]
    powers = torch.arange(M, dtype=torch.float32)
    x_powers = torch.pow(x, powers)
    y = torch.matmul(x_powers, w)
    return y

In [93]:
def fit_polynomial_ls(x, t, M):
    """ 
    Implement a least squares solver for fitting polynomial functions using PyTorch's linear algebra modules.
    
    Args:
    - x (torch.Tensor): Input data points of shape (N, 1)
    - t (torch.Tensor): Target values of shape (N, 1)
    - M (int): Polynomial degree
    
    Returns:
    - w_hat (torch.Tensor): Optimum weight vector of shape (M+1, 1)
    """
    x_powers = torch.pow(x, torch.arange(M+1, dtype=torch.float32))
    w_hat = torch.linalg.lstsq(x_powers, t).solution
    return w_hat


In [81]:
# Define weight vector
w = torch.tensor([1, 2, 3], dtype=torch.float32).reshape(3, 1)
w

tensor([[1.],
        [2.],
        [3.]])

In [82]:
# Generate training set
x_train = 40.0 * (torch.rand(20, dtype=torch.float32) - 0.5).reshape(20, 1)
y_train = polynomial_fun(w, x_train)
noise_train = (0.2 * torch.randn(20, dtype=torch.float32)).reshape(20, 1)
t_train = y_train + noise_train

In [89]:
# Generate testing set
x_test = 40.0 * (torch.rand(10, dtype=torch.float32) - 0.5).reshape(10, 1)
y_test = polynomial_fun(w, x_test)
noise_test = 0.2 * torch.randn(10, dtype=torch.float32).reshape(10, 1)
t_test = y_test + noise_test

In [94]:
w_hat_ls = fit_polynomial_ls(x_train, t_train, M=3)

In [97]:
w_hat_ls

tensor([[1.0654e+00],
        [1.9928e+00],
        [2.9997e+00],
        [1.8975e-05]])

In [66]:
x_train.shape

torch.Size([20, 1])

In [68]:
x_train

tensor([[ -2.3806],
        [  8.0530],
        [ -5.2423],
        [-10.3369],
        [  8.7809],
        [ -9.9948],
        [-15.2973],
        [  9.7244],
        [ 10.7236],
        [-13.5882],
        [ -0.6753],
        [ -6.4381],
        [-13.3195],
        [ 18.4491],
        [ -8.8165],
        [  1.8132],
        [ -7.6747],
        [ 14.4242],
        [-13.1464],
        [  1.9722]])

In [69]:
w

tensor([[1.],
        [2.],
        [3.]])

In [71]:
M = w.shape[0]
powers = torch.arange(M, dtype=torch.float32)
x_power = torch.pow(x_train, powers)

In [78]:
y_train.shape

torch.Size([20, 1])